# Generated by Django 6.0.6 on 2026-06-18 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstronomickyObjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název')),
                ('katalogove_cislo', models.CharField(blank=True, max_length=30, verbose_name='Katalogové číslo (Messier / NGC)')),
                ('popis', models.TextField(verbose_name='Popis')),
                ('vzdalenost_ly', models.FloatField(blank=True, null=True, verbose_name='Vzdálenost (světelné roky)')),
                ('jasnost', models.FloatField(blank=True, null=True, verbose_name='Zdánlivá jasnost (mag)')),
                ('obtiznost_pozorovani', models.IntegerField(choices=[(1, '⭐ Snadný'), (2, '⭐⭐ Střední'), (3, '⭐⭐⭐ Náročný'), (4, '⭐⭐⭐⭐ Expert')], default=1, verbose_name='Obtížnost pozorování')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='objekty/', verbose_name='Fotografie')),
                ('datum_pridani', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum přidání')),
                ('je_featured', models.BooleanField(default=False, verbose_name='Doporučený objekt')),
            ],
            options={
                'verbose_name': 'Astronomický objekt',
                'verbose_name_plural': 'Astronomické objekty',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Pozorovatelna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název')),
                ('misto', models.CharField(max_length=200, verbose_name='Místo')),
                ('nadmorska_vyska', models.IntegerField(blank=True, null=True, verbose_name='Nadmořská výška (m)')),
                ('popis', models.TextField(blank=True, verbose_name='Popis')),
                ('svetelne_znecisteni', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=5, verbose_name='Světelné znečištění (Bortle 1–9)')),
                ('web', models.URLField(blank=True, verbose_name='Web')),
            ],
            options={
                'verbose_name': 'Pozorovatelna',
                'verbose_name_plural': 'Pozorovatelny',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Souhrezdí',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název')),
                ('zkratka', models.CharField(max_length=5, verbose_name='Zkratka IAU')),
                ('popis', models.TextField(blank=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Souhvězdí',
                'verbose_name_plural': 'Souhvězdí',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='TypObjektu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název typu')),
                ('ikona', models.CharField(default='⭐', max_length=10, verbose_name='Ikona (emoji)')),
                ('popis', models.TextField(blank=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Typ objektu',
                'verbose_name_plural': 'Typy objektů',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Pozorování',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum pozorování')),
                ('popis', models.TextField(blank=True, verbose_name='Poznámky z pozorování')),
                ('kvalita_oblohy', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Kvalita oblohy (1–5)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pozorovani/', verbose_name='Fotografie z pozorování')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozorovani', to='katalog.astronomickyobjekt', verbose_name='Objekt')),
                ('pozorovatelna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pozorovani', to='katalog.pozorovatelna', verbose_name='Pozorovatelna')),
            ],
            options={
                'verbose_name': 'Pozorování',
                'verbose_name_plural': 'Pozorování',
                'ordering': ['-datum'],
            },
        ),
        migrations.AddField(
            model_name='astronomickyobjekt',
            name='souhvezdi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objekty', to='katalog.souhrezdí', verbose_name='Souhvězdí'),
        ),
        migrations.AddField(
            model_name='astronomickyobjekt',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objekty', to='katalog.typobjektu', verbose_name='Typ objektu'),
        ),
    ]
